### ISSUE TITLE
Configure NTP on Genesis node

### ISSUE THREAD

**Issue by darrendejaeger** [att-comdev/ucp-integration#5]
I think it would be helpful to have a way in which we're able to specify, and in turn have set, NTP configuration on the Genesis host in an automated fashion. I believe MaaS will do this for you on nodes in a multinode scenario when the site is deployed, but we're currently left with a manual configuration for the Genesis host. This could potentially cause Ceph issues and in "worst-case" scenarios, certificate/image pulling issues.

**Comment by craiganderson** [comment]
IMO a few lines should be added early in the genesis.sh script generated to install ntp client and run an ntpdate to set current time (much like MaaS does on nodes it commissions). It should be done at this early part in the process so that subsequent options do not fail (certificate expiration failures if node with really bad time tries to pull docker images, etc).

**Comment by sh8121att** [comment]
This should be part of the network configuration that is in the 'manually build genesis' step prior to UCP engaging. Otherwise if NTP access isn't working, we've started the genesis build process and still don't have good time. It should fail faster. I'm guessing/hoping at some point this manual configuration becomes some sort of WAN PXE + cloud-init so it is automated as well.

**Comment by craiganderson** [comment]
I'm agreeable with making it part of the manual part of initializing the genesis host. I can update the docs in that case.

**Comment by craiganderson** [comment]
Addressed in documentation in https://review.gerrithub.io/#/c/391326/
